import {build} from 'esbuild';
import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('.', import.meta.url)));
await build({entryPoints:['editor.js'], bundle:true, format:'iife', target:['es2020'],
  minify:true, legalComments:'eof', outfile:'../../atlas_data/site/vendor/coq-editor.js'});
const packages=['@codemirror/commands','@codemirror/language','@codemirror/search',
  '@codemirror/state','@codemirror/view','@lezer/highlight','@lezer/common','@lezer/lr',
  'crelt','style-mod','w3c-keyname'];
let notices='CodeMirror 6 and bundled dependencies. Generated by tool/editor/build.mjs.\n';
for (const name of packages) {
  notices+='\n'+name+'\n'+await readFile('node_modules/'+name+'/LICENSE','utf8');
}
await writeFile('../../atlas_data/site/vendor/coq-editor.LICENSE.txt',notices);
