import {build} from 'esbuild';
import {readFile, writeFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
process.chdir(fileURLToPath(new URL('.', import.meta.url)));
const result=await build({entryPoints:['editor.js'], bundle:true, format:'iife', target:['es2020'],metafile:true,
  minify:true, legalComments:'eof', outfile:'../../atlas_data/site/vendor/coq-editor.js'});
// Derive notices from actual bundled inputs, including transitive packages.
const packages=new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const parts=input.split('/'),index=parts.lastIndexOf('node_modules');
  if(index>=0)packages.add(parts.slice(0,index+(parts[index+1].startsWith('@')?3:2)).join('/'));
}
let notices='CodeMirror 6 and bundled dependencies. Generated by tool/editor/build.mjs.\n';
for (const directory of [...packages].sort()) {
  const manifest=JSON.parse(await readFile(directory+'/package.json','utf8'));
  notices+='\n'+manifest.name+' '+manifest.version+'\n'+await readFile(directory+'/LICENSE','utf8');
}
await writeFile('../../atlas_data/site/vendor/coq-editor.LICENSE.txt',notices);
