(* ========================================================================== *)
(*  DisCoCat.v — categorical compositional distributional semantics           *)
(*  FORMAL-ATLAS / atlas/categorical                                          *)
(* ========================================================================== *)
(*
   SOURCES
     [CSC10] Coecke, B., Sadrzadeh, M. & Clark, S. (2010). Mathematical
       foundations for a compositional distributional model of meaning.
       Lambek Festschrift / Linguistic Analysis 36.  [§2.2 pregroups
       pp. 4-6; §3.1/§3.3 compact closed categories and the graphical
       calculus pp. 8-14; §3.4-3.5 the product category and the meaning
       map, Defs 3.1-3.2 pp. 14-16; §4.1-4.2 Examples 1, 1b, 2
       pp. 17-23; §5 Examples 3-7 pp. 24-27; §6 FRel p. 28]
     [L08]  Lambek, J. (2008). From Word to Sentence: a computational
       algebraic approach to grammar.  [ch. 3 p. 5; ch. 4 pp. 8-10;
       ch. 27 pp. 74-78; ch. 30 p. 84 rules (1)-(14)]
     [PL07] Preller, A. & Lambek, J. (2007). Free compact 2-categories.
       MSCS 17(1).  [§3 p. 313 eq. (3.1); §4 p. 316 iterated adjoints]
     [SCC13] Sadrzadeh, M., Clark, S. & Coecke, B. (2013). The Frobenius
       anatomy of word meanings I: subject and object relative pronouns.
       J. Logic & Computation.  [§2 pp. 3-4; §4 pp. 8-9; §5 pp. 9-10]
     [CGS13] Coecke, B., Grefenstette, E. & Sadrzadeh, M. (2013).
       Lambek vs Lambek. APAL 164.  [Defs 4.1-4.2]
   Design document: formalizing_formal_semantics/atlas/designs/discocat.md
     (a judged synthesis; the constructor shapes, the phantom-dimension
     matrices and all stdlib lemma names below are probe-verified there).

   WHAT IS FORMALIZED
     Part 1  The free pregroup on a set of basic types, as a CALCULUS:
             simple types (b, z) with an integer adjoint iterator,
             compound types as lists, proof-relevant reductions
             Red : Ty -> Ty -> Type generated by reflexivity,
             transitivity, tensor, and the four simple contraction/
             expansion steps; Le := inhabited Red.  Preorder, tensor and
             substitutivity; adjoint cancellation (a^l)^r = a and the
             compound laws (xy)^l = y^l x^l; iterated adjoints; the
             fidelity theorem that Le is NOT antisymmetric on strings
             (the free pregroup is a quotient we deliberately never
             form); the sentence reductions for "John likes Mary"
             n (n^r s n^l) n -> s, intransitives, adjectives, and the
             negative transitive sentence of CSC10 §2.2/§4.2.
     Part 2  The equational theory deq of the free strict compact
             closed category on derivations (heterogeneous in the
             endpoints): congruence, category laws, strict monoidal
             laws, interchange, cast-invisibility, and the four snake
             (yanking) equations; all bracketings/orders of the
             transitive-sentence reduction proved deq-equal.
     Part 3  The concrete model FVect_Q: matrices as functions with
             phantom dimensions, row-major Kronecker, eps/eta as delta
             row/column; category laws, interchange, STRICT monoidal
             laws on the nose, the four snake equations at every
             dimension, eps = inner product, trace eps.eta = dim.
     Part 4  The meaning map F : Red p q -> mat (dimT q) (dimT p) by
             structural recursion, strictly monoidal on objects;
             functoriality equations (definitional, stated); cast
             invariance; and the substantive theorem F_deq: F respects
             the FULL equational theory — well-definedness of meanings
             relative to the calculus; corollaries: all readings of the
             transitive sentence have equal meaning; closed forms for
             intransitive sentences.
     Part 5  Worked examples by vm_compute (CSC10 §4.1, §5): "John
             likes Mary" at N = Q^4 with S = Q^1 and S = Q^2, true and
             false instances; "John sleeps"; the graded likes =
             3/4 loves + 1/4 hates with inner products 3/4, 1/4, 0;
             computational reflection of reading-equality by mat_eqb.

   NOT FORMALIZED (and why)
     * Antisymmetry / the poset quotient (L08 rule (5)): Le is honestly
       a preorder (T9 proves antisymmetry FAILS on strings); the
       quotient is never formed — the meaning map lives at the preorder
       level.
     * Preller's freeness/combing theorem and completeness of deq for
       planar diagrams; Buszkowski's decidability; category-theoretic
       abstractions (no Category/Functor records — every law is a named
       theorem about the concrete model).
     * Real scalars, norms, cosines (CSC10 Def 5.1 divides by norms; Q
       has no sqrt and the paper "implicitly normalises" p. 26): exact
       rational inner products are reported instead.
     * Distinct spaces V (men) / W (women) of §4.1: the functor forces
       F(n) = N (SCC13 §4), so N = span(men + women) — documented
       collapse.
     * STRETCH items of the design (negative-sentence computation at
       dim 2, Frobenius relative pronouns, Lambek single-step
       equivalence, ordered basic types, parser, semiring/FRel):
       dropped for budget; full plans in the design doc (S1-S7).

   REPRESENTATION CHOICES AND ARTIFACT CLASSES
     [ARTIFACT-i]   Not triggered: Red, deq are first-order indexed
                    inductives; no positivity workaround anywhere — a
                    checked absence.
     [ARTIFACT-ii]  (a) Red lives in Type so the meaning map can
                    eliminate into matrices; Le = inhabited Red is its
                    Prop shadow — the sources' "reduction relation" is
                    the pair.  (b) FVect objects are nat VALUES and
                    mat m n is a phantom alias of nat -> nat -> Q:
                    dimension errors are not type errors; correctness is
                    carried by mat_eq and the explicit mmul/kron
                    dimension arguments; this is what makes the monoidal
                    structure strict on the nose.  (c) F(x^l) = F(x) is
                    DEFINITIONAL (dimS ignores the iterator), so the
                    source's self-duality is not a theorem here.
     [ARTIFACT-iii] Qeq is a setoid (all model laws are mat_eq;
                    rewriting needs the Proper instances); vectors are
                    functions with junk outside the dimension bounds;
                    everything on the vm_compute path is transparent
                    (Defined/Definition, no Qed casts); unary nat
                    div/mod bounds example sizes (<= 512 columns
                    instant).
     [ARTIFACT-iv]  No category/functor classes, no dependent
                    fixed-size vectors (they force casts on
                    associativity), no bigops (qsum + its kit), no
                    quotient types (deq is an explicit equational
                    theory).
     [ARTIFACT-v]   Grammaticality is decidable in the literature but
                    derivations here are hand-written terms;
                    mat_eq at fixed dims IS decided (mat_eqb), so
                    semantic consequences of deq are reflected
                    computationally even where syntactic deq is not.
     Zero axioms: every audited theorem closes under the global context.
*)

From Coq Require Import List ZArith QArith Arith Lia Bool.
Import ListNotations.

(* ========================================================================== *)
(*  Part 1 — The free pregroup calculus (module Pregroup)                     *)
(* ========================================================================== *)

Section Pregroup.

Variable B : Type.

(* D1.  Simple types with an integer adjoint iterator: PL07 p. 316;
   L08 ch. 4 p. 8.  (a^l)^r = a is lia on Z — an honest equality. *)
Definition Simple : Type := (B * Z)%type.
Definition ladj (a : Simple) : Simple := (fst a, Z.pred (snd a)).
Definition radj (a : Simple) : Simple := (fst a, Z.succ (snd a)).

(* D2.  Compound types: the free monoid as lists (L08 ch. 4 p. 9). *)
Definition Ty : Type := list Simple.

(* D3.  Adjoints of compound types: Preller's
   (A1^(z1)...An^(zn))^l = An^(zn-1)...A1^(z1-1)  (PL07 p. 316). *)
Definition ladj_ty (p : Ty) : Ty := rev (map ladj p).
Definition radj_ty (p : Ty) : Ty := rev (map radj p).

(* D5.  Proof-relevant reductions.  The four structural steps are
   indexed by ladj a / radj a so that every yanking equation is
   cast-free (design verdict; probe-verified): L08 ch. 30 rules
   (3),(4),(6),(8),(9); CSC10 §2.2 p. 5, §3.3 p. 13. *)
Inductive Red : Ty -> Ty -> Type :=
| red_refl   (p : Ty) : Red p p
| red_trans  {p q r : Ty} : Red p q -> Red q r -> Red p r
| red_cup_l  (a : Simple) : Red [ladj a; a] []          (* a^l a <= 1 *)
| red_cup_r  (a : Simple) : Red [a; radj a] []          (* a a^r <= 1 *)
| red_cap_l  (a : Simple) : Red [] [a; ladj a]          (* 1 <= a a^l *)
| red_cap_r  (a : Simple) : Red [] [radj a; a]          (* 1 <= a^r a *)
| red_tensor {p q p' q' : Ty} : Red p p' -> Red q q' -> Red (p ++ q) (p' ++ q').

(* D4.  The order (CSC10 §2.2 p. 4): the Prop shadow of Red
   (ARTIFACT-ii). *)
Definition Le (p q : Ty) : Prop := inhabited (Red p q).

(* D6.  Casts along list equalities — needed only by the compound
   adjoint laws; deq_cast makes them semantically invisible. *)
Definition red_cast {p p' q q' : Ty} (e1 : p = p') (e2 : q = q')
  (d : Red p q) : Red p' q' :=
  match e1 in (_ = x), e2 in (_ = y) return Red x y with
  | eq_refl, eq_refl => d
  end.

(* D7.  Substitutivity, cast-free (u ++ p ++ v is right-nested):
   L08 ch. 27 p. 74 rule (7). *)
Definition red_subst (u v : Ty) {p q : Ty} (d : Red p q) :
  Red (u ++ p ++ v) (u ++ q ++ v) :=
  red_tensor (red_refl u) (red_tensor d (red_refl v)).

(* D9.  The equational theory of the free STRICT compact closed
   category on derivations — heterogeneous in the endpoints, so the
   strict monoidal laws relate derivations whose index lists are only
   propositionally equal, without transports: CSC10 §3.1 eqs (1)-(3)
   pp. 8-9, §3.3 p. 11 (the four yanking equations); PL07 (3.1). *)
Inductive deq : forall {p q p' q' : Ty}, Red p q -> Red p' q' -> Prop :=
| deq_refl {p q} (d : Red p q) : deq d d
| deq_sym {p q p' q'} (d : Red p q) (d' : Red p' q') :
    deq d d' -> deq d' d
| deq_trans {p1 q1 p2 q2 p3 q3}
    (d1 : Red p1 q1) (d2 : Red p2 q2) (d3 : Red p3 q3) :
    deq d1 d2 -> deq d2 d3 -> deq d1 d3
| deq_cong_trans {p q r p' q' r'}
    (d1 : Red p q) (d2 : Red q r) (d1' : Red p' q') (d2' : Red q' r') :
    deq d1 d1' -> deq d2 d2' ->
    deq (red_trans d1 d2) (red_trans d1' d2')
| deq_cong_tensor {p1 q1 p2 q2 p1' q1' p2' q2'}
    (d1 : Red p1 q1) (d2 : Red p2 q2)
    (d1' : Red p1' q1') (d2' : Red p2' q2') :
    deq d1 d1' -> deq d2 d2' ->
    deq (red_tensor d1 d2) (red_tensor d1' d2')
| deq_assoc {p q r t} (d1 : Red p q) (d2 : Red q r) (d3 : Red r t) :
    deq (red_trans (red_trans d1 d2) d3) (red_trans d1 (red_trans d2 d3))
| deq_unit_l {p q} (d : Red p q) : deq (red_trans (red_refl p) d) d
| deq_unit_r {p q} (d : Red p q) : deq (red_trans d (red_refl q)) d
| deq_tensor_assoc {p1 q1 p2 q2 p3 q3}
    (d1 : Red p1 q1) (d2 : Red p2 q2) (d3 : Red p3 q3) :
    deq (red_tensor (red_tensor d1 d2) d3)
        (red_tensor d1 (red_tensor d2 d3))
| deq_tensor_unit_l {p q} (d : Red p q) :
    deq (red_tensor (red_refl []) d) d
| deq_tensor_unit_r {p q} (d : Red p q) :
    deq (red_tensor d (red_refl [])) d
| deq_tensor_refl (p q : Ty) :
    deq (red_tensor (red_refl p) (red_refl q)) (red_refl (p ++ q))
| deq_interchange {p1 q1 r1 p2 q2 r2}
    (f1 : Red p1 q1) (g1 : Red q1 r1) (f2 : Red p2 q2) (g2 : Red q2 r2) :
    deq (red_trans (red_tensor f1 f2) (red_tensor g1 g2))
        (red_tensor (red_trans f1 g1) (red_trans f2 g2))
| deq_cast {p q p' q'} (e1 : p = p') (e2 : q = q') (d : Red p q) :
    deq (red_cast e1 e2 d) d
| deq_snake_1 (a : Simple) :
    deq (red_trans (red_tensor (red_cap_l a) (red_refl [a]))
                   (red_tensor (red_refl [a]) (red_cup_l a)))
        (red_refl [a])
| deq_snake_2 (a : Simple) :
    deq (red_trans (red_tensor (red_refl [a]) (red_cap_r a))
                   (red_tensor (red_cup_r a) (red_refl [a])))
        (red_refl [a])
| deq_snake_3 (a : Simple) :
    deq (red_trans (red_tensor (red_refl [ladj a]) (red_cap_l a))
                   (red_tensor (red_cup_l a) (red_refl [ladj a])))
        (red_refl [ladj a])
| deq_snake_4 (a : Simple) :
    deq (red_trans (red_tensor (red_cap_r a) (red_refl [radj a]))
                   (red_tensor (red_refl [radj a]) (red_cup_r a)))
        (red_refl [radj a]).

(* -------------------------------------------------------------------- *)
(*  T1-T2.  Le is a preorder, compatible with tensor and contexts:      *)
(*  L08 rules (3),(4),(6),(7); CSC10 §2.2 p. 4.                          *)
(* -------------------------------------------------------------------- *)

Theorem Le_refl : forall p, Le p p.
Proof. intros p; exact (inhabits (red_refl p)). Qed.

Theorem Le_trans : forall p q r, Le p q -> Le q r -> Le p r.
Proof.
  intros p q r [d1] [d2]; exact (inhabits (red_trans d1 d2)).
Qed.

Theorem Le_tensor : forall p q p' q',
  Le p p' -> Le q q' -> Le (p ++ q) (p' ++ q').
Proof.
  intros p q p' q' [d1] [d2]; exact (inhabits (red_tensor d1 d2)).
Qed.

Theorem Le_subst : forall u v p q,
  Le p q -> Le (u ++ p ++ v) (u ++ q ++ v).
Proof.
  intros u v p q [d]; exact (inhabits (red_subst u v d)).
Qed.

(* T3.  Adjoint laws for simple types, including iterated adjoints:
   CSC10 p. 5; L08 ch. 30. *)
Theorem Le_cup_l : forall a, Le [ladj a; a] [].
Proof. intros a; exact (inhabits (red_cup_l a)). Qed.

Theorem Le_cup_r : forall a, Le [a; radj a] [].
Proof. intros a; exact (inhabits (red_cup_r a)). Qed.

Theorem Le_cap_l : forall a, Le [] [a; ladj a].
Proof. intros a; exact (inhabits (red_cap_l a)). Qed.

Theorem Le_cap_r : forall a, Le [] [radj a; a].
Proof. intros a; exact (inhabits (red_cap_r a)). Qed.

Theorem Le_cup_ll : forall a, Le [ladj (ladj a); ladj a] [].
Proof. intros a; exact (inhabits (red_cup_l (ladj a))). Qed.

Theorem Le_cap_rr : forall a, Le [] [radj (radj a); radj a].
Proof. intros a; exact (inhabits (red_cap_r (radj a))). Qed.

(* T5.  Opposite adjoints annihilate — honest equalities of types:
   L08 (13), ch. 27 (4); CSC10 p. 5; PL07 p. 316. *)
Theorem radj_ladj : forall a, radj (ladj a) = a.
Proof.
  intros [b z]; unfold radj, ladj; simpl; f_equal; lia.
Qed.

Theorem ladj_radj : forall a, ladj (radj a) = a.
Proof.
  intros [b z]; unfold radj, ladj; simpl; f_equal; lia.
Qed.

Theorem radj_ty_ladj_ty : forall p, radj_ty (ladj_ty p) = p.
Proof.
  intros p; unfold radj_ty, ladj_ty.
  rewrite map_rev, rev_involutive, map_map.
  rewrite (map_ext _ id) by (intros a; apply radj_ladj).
  apply map_id.
Qed.

Theorem ladj_ty_radj_ty : forall p, ladj_ty (radj_ty p) = p.
Proof.
  intros p; unfold radj_ty, ladj_ty.
  rewrite map_rev, rev_involutive, map_map.
  rewrite (map_ext _ id) by (intros a; apply ladj_radj).
  apply map_id.
Qed.

(* T6.  The compound adjoint is an anti-homomorphism:
   L08 (11),(12); CSC10 p. 5. *)
Theorem ladj_ty_app : forall p q,
  ladj_ty (p ++ q) = ladj_ty q ++ ladj_ty p.
Proof.
  intros p q; unfold ladj_ty; rewrite map_app, rev_app_distr; reflexivity.
Qed.

Theorem radj_ty_app : forall p q,
  radj_ty (p ++ q) = radj_ty q ++ radj_ty p.
Proof.
  intros p q; unfold radj_ty; rewrite map_app, rev_app_distr; reflexivity.
Qed.

Theorem ladj_ty_nil : ladj_ty [] = [].
Proof. reflexivity. Qed.

Theorem radj_ty_nil : radj_ty [] = [].
Proof. reflexivity. Qed.

(* T9.  Fidelity: Le is a PREORDER, not a partial order — a and
   a a^r a reduce to each other but differ as strings; the free
   pregroup is the quotient we deliberately do not form (ARTIFACT-v):
   L08 ch. 30 (5); PL07 p. 310. *)
Theorem le_not_antisymmetric : forall a,
  Le [a] [a; radj a; a] /\ Le [a; radj a; a] [a] /\
  [a] <> [a; radj a; a].
Proof.
  intros a; refine (conj _ (conj _ _)).
  - exact (inhabits (red_tensor (red_refl [a]) (red_cap_r a))).
  - exact (inhabits (red_tensor (red_cup_r a) (red_refl [a]))).
  - intros H; inversion H.
Qed.

(* T11.  deq only relates derivations with (propositionally) equal
   endpoints. *)
Theorem deq_endpoints : forall p q p' q' (d : Red p q) (d' : Red p' q'),
  deq d d' -> p = p' /\ q = q'.
Proof.
  intros p q p' q' d d' H; induction H;
    repeat match goal with
    | IH : _ /\ _ |- _ => destruct IH
    end; subst; try (split; reflexivity).
  - (* tensor_assoc *) split; symmetry; apply app_assoc.
  - (* tensor_unit_r *) split; apply app_nil_r.
Qed.

End Pregroup.

(* Implicits do not survive End (probe-verified): re-declare. *)
Arguments Simple B : clear implicits.
Arguments Ty B : clear implicits.
Arguments ladj {B} a.
Arguments radj {B} a.
Arguments ladj_ty {B} p.
Arguments radj_ty {B} p.
Arguments Red {B}.
Arguments red_refl {B} p.
Arguments red_trans {B p q r}.
Arguments red_cup_l {B} a.
Arguments red_cup_r {B} a.
Arguments red_cap_l {B} a.
Arguments red_cap_r {B} a.
Arguments red_tensor {B p q p' q'}.
Arguments red_cast {B p p' q q'}.
Arguments red_subst {B} u v {p q}.
Arguments Le {B}.
Arguments deq {B p q p' q'}.
Arguments deq_refl {B p q} d.
Arguments deq_sym {B p q p' q'} d d'.
Arguments deq_trans {B p1 q1 p2 q2 p3 q3} d1 d2 d3.
Arguments deq_cong_trans {B p q r p' q' r'} d1 d2 d1' d2'.
Arguments deq_cong_tensor {B p1 q1 p2 q2 p1' q1' p2' q2'} d1 d2 d1' d2'.
Arguments deq_assoc {B p q r t} d1 d2 d3.
Arguments deq_unit_l {B p q} d.
Arguments deq_unit_r {B p q} d.
Arguments deq_tensor_assoc {B p1 q1 p2 q2 p3 q3} d1 d2 d3.
Arguments deq_tensor_unit_l {B p q} d.
Arguments deq_tensor_unit_r {B p q} d.
Arguments deq_tensor_refl {B} p q.
Arguments deq_interchange {B p1 q1 r1 p2 q2 r2} f1 g1 f2 g2.
Arguments deq_cast {B p q p' q'} e1 e2 d.
Arguments deq_snake_1 {B} a.
Arguments deq_snake_2 {B} a.
Arguments deq_snake_3 {B} a.
Arguments deq_snake_4 {B} a.

(* ========================================================================== *)
(*  Part 1b — Example grammar: types and derivations (CSC10 §2.2, §4)         *)
(* ========================================================================== *)

Module Examples.

(* D12.  Basic types (names Bn.. avoid shadowing n, s): CSC10 §2.2
   pp. 5-6; Bsig is the sigma of the negation example §4.2. *)
Inductive basic := Bn | Bs | Bj | Bsig.

Definition n  : Simple basic := (Bn, 0%Z).
Definition s  : Simple basic := (Bs, 0%Z).
Definition jj : Simple basic := (Bj, 0%Z).
Definition sg : Simple basic := (Bsig, 0%Z).

Definition tv   : Ty basic := [radj n; s; ladj n].          (* n^r s n^l *)
Definition iv   : Ty basic := [radj n; s].                  (* n^r s     *)
Definition adjt : Ty basic := [n; ladj n].                  (* n n^l     *)
Definition does : Ty basic := [radj n; s; ladj jj; sg].
Definition nott : Ty basic := [radj sg; jj; ladj jj; sg].
Definition likew : Ty basic := [radj sg; jj; ladj n].

(* D13.  Derivation terms — closed, cast-free (++ on literals converts):
   CSC10 p. 6 (step-by-step reduction), p. 14 (the parallel morphism
   eps^r_n (x) 1_s (x) eps^l_n). *)
Definition tv_red : Red [n; radj n; s; ladj n; n] [s] :=
  red_tensor (red_cup_r n) (red_tensor (red_refl [s]) (red_cup_l n)).

Definition tv_layer_subj1 : Red [n; radj n; s; ladj n; n] [s; ladj n; n] :=
  red_tensor (red_cup_r n) (red_refl [s; ladj n; n]).
Definition tv_layer2 : Red [s; ladj n; n] [s] :=
  red_tensor (red_refl [s]) (red_cup_l n).
Definition tv_red_subj : Red [n; radj n; s; ladj n; n] [s] :=
  red_trans tv_layer_subj1 tv_layer2.

Definition tv_layer_obj1 : Red [n; radj n; s; ladj n; n] [n; radj n; s] :=
  red_tensor (red_refl [n; radj n; s]) (red_cup_l n).
Definition tv_layer_obj2 : Red [n; radj n; s] [s] :=
  red_tensor (red_cup_r n) (red_refl [s]).
Definition tv_red_obj : Red [n; radj n; s; ladj n; n] [s] :=
  red_trans tv_layer_obj1 tv_layer_obj2.

Definition tv_red_alt : Red [n; radj n; s; ladj n; n] [s] :=
  red_tensor (red_tensor (red_cup_r n) (red_refl [s])) (red_cup_l n).

Definition iv_red : Red [n; radj n; s] [s] :=
  red_tensor (red_cup_r n) (red_refl [s]).

Definition adj_red : Red [n; ladj n; n] [n] :=
  red_tensor (red_refl [n]) (red_cup_l n).

(* The negative transitive sentence "John does not like Mary"
   (CSC10 §2.2 p. 6, §4.2 p. 21): two layers of contractions. *)
Definition neg_layer1 :
  Red (n :: does ++ nott ++ likew ++ [n]) [s; ladj jj; jj; ladj jj; jj] :=
  red_tensor (red_cup_r n)
    (red_tensor (red_refl [s])
      (red_tensor (red_refl [ladj jj])
        (red_tensor (red_cup_r sg)
          (red_tensor (red_refl [jj])
            (red_tensor (red_refl [ladj jj])
              (red_tensor (red_cup_r sg)
                (red_tensor (red_refl [jj]) (red_cup_l n)))))))).
Definition neg_layer2 : Red [s; ladj jj; jj; ladj jj; jj] [s] :=
  red_tensor (red_refl [s]) (red_tensor (red_cup_l jj) (red_cup_l jj)).
Definition neg_red : Red (n :: does ++ nott ++ likew ++ [n]) [s] :=
  red_trans neg_layer1 neg_layer2.

(* T10.  The sentence reductions, at the order level: CSC10 p. 6
   "n (n^r s n^l) n -> s"; L08 ch. 3 p. 5. *)
Theorem Le_tv : Le [n; radj n; s; ladj n; n] [s].
Proof. exact (inhabits tv_red). Qed.

Theorem Le_iv : Le [n; radj n; s] [s].
Proof. exact (inhabits iv_red). Qed.

Theorem Le_adj : Le [n; ladj n; n] [n].
Proof. exact (inhabits adj_red). Qed.

Theorem Le_neg : Le (n :: does ++ nott ++ likew ++ [n]) [s].
Proof. exact (inhabits neg_red). Qed.

(* -------------------------------------------------------------------- *)
(*  T12.  All readings of "John likes Mary" are equal in the free       *)
(*  compact closed category (CSC10 p. 9: provable from the axioms iff   *)
(*  derivable in the graphical language; here: the axioms suffice for   *)
(*  the readings that arise).                                            *)
(* -------------------------------------------------------------------- *)

Theorem deq_tv_alt : deq tv_red_alt tv_red.
Proof.
  exact (deq_tensor_assoc (red_cup_r n) (red_refl [s]) (red_cup_l n)).
Qed.

Theorem deq_tv_subj : deq tv_red_subj tv_red.
Proof.
  exact (deq_trans _ _ _
    (deq_trans _ _ _
      (deq_trans _ _ _
        (deq_cong_trans _ _ _ _
           (deq_cong_tensor _ _ _ _
              (deq_refl (red_cup_r n))
              (deq_sym _ _ (deq_tensor_refl [s] [ladj n; n])))
           (deq_refl tv_layer2))
        (deq_cong_trans _ _ _ _
           (deq_sym _ _
              (deq_tensor_assoc (red_cup_r n) (red_refl [s])
                 (red_refl [ladj n; n])))
           (deq_refl tv_layer2)))
      (deq_interchange
         (red_tensor (red_cup_r n) (red_refl [s])) (red_refl [s])
         (red_refl [ladj n; n]) (red_cup_l n)))
    (deq_trans _ _ _
      (deq_cong_tensor _ _ _ _
         (deq_unit_r (red_tensor (red_cup_r n) (red_refl [s])))
         (deq_unit_l (red_cup_l n)))
      (deq_tensor_assoc (red_cup_r n) (red_refl [s]) (red_cup_l n)))).
Qed.

Theorem deq_tv_obj : deq tv_red_obj tv_red.
Proof.
  exact (deq_trans _ _ _
    (deq_trans _ _ _
      (deq_trans _ _ _
        (deq_cong_trans _ _ _ _
           (deq_cong_tensor _ _ _ _
              (deq_sym _ _ (deq_tensor_refl [n; radj n] [s]))
              (deq_refl (red_cup_l n)))
           (deq_refl tv_layer_obj2))
        (deq_cong_trans _ _ _ _
           (deq_tensor_assoc (red_refl [n; radj n]) (red_refl [s])
              (red_cup_l n))
           (deq_refl tv_layer_obj2)))
      (deq_interchange
         (red_refl [n; radj n]) (red_cup_r n)
         (red_tensor (red_refl [s]) (red_cup_l n)) (red_refl [s])))
    (deq_cong_tensor _ _ _ _
       (deq_unit_l (red_cup_r n))
       (deq_unit_r (red_tensor (red_refl [s]) (red_cup_l n))))).
Qed.

End Examples.

(* ========================================================================== *)
(*  Part 3 — The concrete model FVect_Q (CSC10 §3.1, §3.3, §6)                *)
(* ========================================================================== *)

Local Open Scope Q_scope.

(* D14.  The Sigma of CSC10 eqs (4)-(5), by primitive recursion on the
   bound (pitfall 5). *)
Fixpoint qsum (n : nat) (f : nat -> Q) : Q :=
  match n with O => 0 | S m => qsum m f + f m end.

(* D15.  Matrices with PHANTOM dimensions (ARTIFACT-ii): the dims live
   in mat_eq and in the explicit mmul/kron arguments, which is what
   makes the monoidal structure strict on the nose. *)
Definition mat (m n : nat) : Type := nat -> nat -> Q.
Definition mat_eq (m n : nat) (A B : nat -> nat -> Q) : Prop :=
  forall i j, (i < m)%nat -> (j < n)%nat -> A i j == B i j.
Definition idm : nat -> nat -> Q :=
  fun i j => if Nat.eqb i j then 1 else 0.
Definition mmul (k : nat) (A B : nat -> nat -> Q) : nat -> nat -> Q :=
  fun i j => qsum k (fun l => A i l * B l j).
(* Row-major Kronecker; m2/n2 are the FULL row/col dims of the right
   factor (pitfall 3). *)
Definition kron (m2 n2 : nat) (A B : nat -> nat -> Q) : nat -> nat -> Q :=
  fun i j => A (i / m2)%nat (j / n2)%nat * B (i mod m2)%nat (j mod n2)%nat.

(* D16.  eps/eta: entry 1 at e_i (x) e_i (CSC10 eqs (4)-(5) pp. 12-13);
   V^l = V^r = V, so both adjoint eps/eta collapse to these. *)
Definition eps (d : nat) : nat -> nat -> Q :=
  fun _ k => if Nat.eqb (k / d)%nat (k mod d)%nat then 1 else 0.
Definition eta (d : nat) : nat -> nat -> Q :=
  fun k _ => if Nat.eqb (k / d)%nat (k mod d)%nat then 1 else 0.

(* D17.  Vectors are columns (CSC10 p. 9). *)
Definition basis (d i : nat) : nat -> nat -> Q :=
  fun r _ => if Nat.eqb r i then 1 else 0.
Definition inner (d : nat) (v w : nat -> nat -> Q) : Q :=
  qsum d (fun i => v i 0%nat * w i 0%nat).
Definition vscale (c : Q) (v : nat -> nat -> Q) : nat -> nat -> Q :=
  fun i j => c * v i j.
Definition vadd (v w : nat -> nat -> Q) : nat -> nat -> Q :=
  fun i j => v i j + w i j.

(* D19.  Decision/display layer (ARTIFACT-v: mat_eq at fixed dims IS
   decidable). *)
Definition mat_eqb (m n : nat) (A B : nat -> nat -> Q) : bool :=
  forallb (fun i => forallb (fun j => Qeq_bool (A i j) (B i j))
                      (seq 0 n)) (seq 0 m).
Definition entries (d : nat) (v : nat -> nat -> Q) : list Q :=
  map (fun i => Qred (v i 0%nat)) (seq 0 d).

(* T24.  The reflection lemma. *)
Theorem mat_eqb_sound : forall m n A B,
  mat_eqb m n A B = true -> mat_eq m n A B.
Proof.
  intros m n A B H i j Hi Hj.
  unfold mat_eqb in H.
  assert (Hi' : In i (seq 0 m)) by (apply in_seq; lia).
  assert (Hj' : In j (seq 0 n)) by (apply in_seq; lia).
  pose proof (proj1 (forallb_forall _ _) H i Hi') as Hrow.
  pose proof (proj1 (forallb_forall _ _) Hrow j Hj') as Hcell.
  apply Qeq_bool_iff, Hcell.
Qed.

(* ========================================================================== *)
(*  Part 4 — The meaning map (CSC10 Def 3.2; SCC13 §4; CGS13 Defs 4.1-4.2)    *)
(* ========================================================================== *)

Section Meaning.

Variable B : Type.
Variable dim : B -> nat.

(* D20.  F on objects: the iterator is ignored — F(x^l) = F(x) is
   DEFINITIONAL (ARTIFACT-ii). *)
Definition dimS (a : Simple B) : nat := dim (fst a).
Definition dimT (p : Ty B) : nat :=
  fold_right (fun a d => (dimS a * d)%nat) 1%nat p.

(* D21.  F on reductions, by structural recursion (probe-verified: no
   return annotation needed thanks to the phantom dims). *)
Fixpoint F {p q : Ty B} (d : Red p q) : nat -> nat -> Q :=
  match d with
  | red_refl _ => idm
  | @red_trans _ _ q0 _ d1 d2 => mmul (dimT q0) (F d2) (F d1)
  | red_cup_l a => eps (dimS a)
  | red_cup_r a => eps (dimS a)
  | red_cap_l a => eta (dimS a)
  | red_cap_r a => eta (dimS a)
  | @red_tensor _ _ q0 _ q0' d1 d2 =>
      kron (dimT q0') (dimT q0) (F d1) (F d2)
  end.

(* D22.  Tensoring the word vectors (right fold aligned with dimT and
   right-nested red_tensor; the kron row-dim is the FULL tail dim —
   pitfall 3). *)
Fixpoint tensor_words (ws : list (Ty B * (nat -> nat -> Q))) :
  nat -> nat -> Q :=
  match ws with
  | [] => fun _ _ => 1
  | (t, v) :: rest =>
      kron (dimT (concat (map fst rest))) 1%nat v (tensor_words rest)
  end.

Definition meaning {p q : Ty B} (d : Red p q)
  (ws : list (Ty B * (nat -> nat -> Q))) : nat -> nat -> Q :=
  mmul (dimT p) (F d) (tensor_words ws).

(* T25.  F is strictly monoidal on objects. *)
Theorem dimT_app : forall p q, dimT (p ++ q) = (dimT p * dimT q)%nat.
Proof.
  induction p as [| a p IH]; intros q; simpl.
  - lia.
  - rewrite IH; apply Nat.mul_assoc.
Qed.

Theorem dimT_ladj : forall p, dimT (ladj_ty p) = dimT p.
Proof.
  induction p as [| a p IH]; simpl; [reflexivity |].
  unfold ladj_ty in *; simpl.
  rewrite dimT_app, IH; simpl.
  rewrite Nat.mul_1_r; apply Nat.mul_comm.
Qed.

Theorem dimT_radj : forall p, dimT (radj_ty p) = dimT p.
Proof.
  induction p as [| a p IH]; simpl; [reflexivity |].
  unfold radj_ty in *; simpl.
  rewrite dimT_app, IH; simpl.
  rewrite Nat.mul_1_r; apply Nat.mul_comm.
Qed.

(* T26.  Functoriality equations — definitional, stated so the brief's
   "functoriality" has an explicit honest form. *)
Theorem F_refl : forall p, F (red_refl p) = idm.
Proof. reflexivity. Qed.

Theorem F_trans : forall p q r (d1 : Red p q) (d2 : Red q r),
  F (red_trans d1 d2) = mmul (dimT q) (F d2) (F d1).
Proof. reflexivity. Qed.

Theorem F_tensor : forall p q p' q' (d1 : Red p p') (d2 : Red q q'),
  F (red_tensor d1 d2) = kron (dimT q') (dimT q) (F d1) (F d2).
Proof. reflexivity. Qed.

Theorem F_cup_l : forall a, F (red_cup_l a) = eps (dimS a).
Proof. reflexivity. Qed.

Theorem F_cap_r : forall a, F (red_cap_r a) = eta (dimS a).
Proof. reflexivity. Qed.

(* T27.  Casts are invisible to the semantics. *)
Theorem F_cast : forall p p' q q' (e1 : p = p') (e2 : q = q')
  (d : Red p q), F (red_cast e1 e2 d) = F d.
Proof. intros p p' q q' e1 e2 d; destruct e1, e2; reflexivity. Qed.

End Meaning.

Arguments dimS {B} dim a.
Arguments dimT {B} dim p.
Arguments F {B} dim {p q} d.
Arguments tensor_words {B} dim ws.
Arguments meaning {B} dim {p q} d ws.

(* ========================================================================== *)
(*  Part 5 — Worked examples by vm_compute (CSC10 §4.1, §5)                   *)
(* ========================================================================== *)

Module ExModel.

Import Examples.

(* D23.  CSC10 §4.1: N = span{m1, m3, f2, f4} (the functor forces one
   space, header note); S = Q^1 (Example 1) or Q^2 (Example 1b). *)
Definition dim1 (b : basic) : nat :=
  match b with Bn => 4 | Bs => 1 | Bj => 1 | Bsig => 4 end.
Definition dim2 (b : basic) : nat :=
  match b with Bn => 4 | Bs => 2 | Bj => 2 | Bsig => 4 end.

Definition m1 := basis 4 0.
Definition m3 := basis 4 1.
Definition f2 := basis 4 2.
Definition f4 := basis 4 3.
Definition john := m3.        (* "John is m3" *)
Definition mary := f4.        (* "Mary is f4" *)

(* likes_ij = 1 iff m_i likes f_j: John(m3) likes Mary(f4); m1 likes f2;
   nothing else. *)
Definition likes_rel (i k : nat) : bool :=
  (Nat.eqb i 1 && Nat.eqb k 3) || (Nat.eqb i 0 && Nat.eqb k 2).

(* S = Q^1: the meaning vector in N (x) S (x) N, row-major i*4 + k. *)
Definition likes1 : nat -> nat -> Q :=
  fun r _ => if likes_rel (r / 4)%nat (r mod 4)%nat then 1 else 0.

(* S = Q^2 (|0> = false, |1> = true): row-major i*8 + t*4 + k. *)
Definition likes2 : nat -> nat -> Q :=
  fun r _ =>
    if Nat.eqb ((r / 4) mod 2)%nat
               (if likes_rel (r / 8)%nat (r mod 4)%nat then 1 else 0)
    then 1 else 0.

(* D24.  Graded verb (CSC10 §5 Example 3): loves/hates truth-tables and
   likes_g = 3/4 loves + 1/4 hates. *)
Definition loves_rel (i k : nat) : bool := Nat.eqb i 1 && Nat.eqb k 3.
Definition hates_rel (i k : nat) : bool := negb (loves_rel i k).
Definition loves : nat -> nat -> Q :=
  fun r _ =>
    if Nat.eqb ((r / 4) mod 2)%nat
               (if loves_rel (r / 8)%nat (r mod 4)%nat then 1 else 0)
    then 1 else 0.
Definition hates : nat -> nat -> Q :=
  fun r _ =>
    if Nat.eqb ((r / 4) mod 2)%nat
               (if hates_rel (r / 8)%nat (r mod 4)%nat then 1 else 0)
    then 1 else 0.
Definition likes_g : nat -> nat -> Q :=
  vadd (vscale (3 # 4) loves) (vscale (1 # 4) hates).

(* D25.  Intransitive: "John sleeps" at S = Q^2, row-major i*2 + t. *)
Definition sleeps_rel (i : nat) : bool := Nat.eqb i 1.
Definition sleeps : nat -> nat -> Q :=
  fun r _ =>
    if Nat.eqb (r mod 2)%nat (if sleeps_rel (r / 2)%nat then 1 else 0)
    then 1 else 0.

Definition nty : Ty basic := [n].

(* T32.  Example 1 (S one-dimensional): "John likes Mary" = 1, the
   false instance (m1 likes f4 is false) = 0.  [CSC10 §4.1 p. 19] *)
Theorem ex1_true :
  entries 1 (meaning dim1 tv_red [(nty, john); (tv, likes1); (nty, mary)])
  = [1].
Proof. vm_compute; reflexivity. Qed.

Theorem ex1_false :
  entries 1 (meaning dim1 tv_red [(nty, m1); (tv, likes1); (nty, mary)])
  = [0].
Proof. vm_compute; reflexivity. Qed.

(* T33.  Example 1b (S = Q^2): |1> for true, |0> for false.  [p. 20] *)
Theorem ex1b_true :
  entries 2 (meaning dim2 tv_red [(nty, john); (tv, likes2); (nty, mary)])
  = [0; 1].
Proof. vm_compute; reflexivity. Qed.

Theorem ex1b_false :
  entries 2 (meaning dim2 tv_red [(nty, m1); (tv, likes2); (nty, mary)])
  = [1; 0].
Proof. vm_compute; reflexivity. Qed.

(* T34.  Intransitive "John sleeps". *)
Theorem ex_iv :
  entries 2 (meaning dim2 iv_red [(nty, john); (iv, sleeps)])
  = [0; 1].
Proof. vm_compute; reflexivity. Qed.

(* T35.  Example 3: the graded sentence 3/4 |1> + 1/4 |0>.  [p. 25] *)
Theorem ex3_graded :
  entries 2 (meaning dim2 tv_red [(nty, john); (tv, likes_g); (nty, mary)])
  = [1 # 4; 3 # 4].
Proof. vm_compute; reflexivity. Qed.

(* T36.  Example 5: exact sentence-level inner products (the paper
   "implicitly normalises"; we report exact rationals).  [pp. 26-27] *)
Theorem ex5_loves_likesg :
  Qred (inner 2
    (meaning dim2 tv_red [(nty, john); (tv, loves); (nty, mary)])
    (meaning dim2 tv_red [(nty, john); (tv, likes_g); (nty, mary)]))
  = 3 # 4.
Proof. vm_compute; reflexivity. Qed.

Theorem ex5_hates_likesg :
  Qred (inner 2
    (meaning dim2 tv_red [(nty, john); (tv, hates); (nty, mary)])
    (meaning dim2 tv_red [(nty, john); (tv, likes_g); (nty, mary)]))
  = 1 # 4.
Proof. vm_compute; reflexivity. Qed.

Theorem ex5_loves_hates :
  Qred (inner 2
    (meaning dim2 tv_red [(nty, john); (tv, loves); (nty, mary)])
    (meaning dim2 tv_red [(nty, john); (tv, hates); (nty, mary)]))
  = 0.
Proof. vm_compute; reflexivity. Qed.

(* T37.  Computational reflection of the reading-equality (T12/T28):
   all four derivations denote the same matrix at dim2. *)
Theorem readings_agree_computationally :
  mat_eqb 2 512 (F dim2 tv_red_subj) (F dim2 tv_red) = true /\
  mat_eqb 2 512 (F dim2 tv_red_obj) (F dim2 tv_red) = true /\
  mat_eqb 2 512 (F dim2 tv_red_alt) (F dim2 tv_red) = true.
Proof.
  refine (conj _ (conj _ _)); vm_compute; reflexivity.
Qed.

End ExModel.

(* ========================================================================== *)
(*  Part 3b — the qsum and index kits (T15-T16): the workhorse                 *)
(* ========================================================================== *)

Lemma qsum_ext : forall n f g,
  (forall i, (i < n)%nat -> f i == g i) -> qsum n f == qsum n g.
Proof.
  induction n as [| m IH]; intros f g H; simpl; [reflexivity |].
  rewrite (IH f g (fun i Hi => H i (Nat.lt_lt_succ_r _ _ Hi))).
  rewrite (H m (Nat.lt_succ_diag_r m)); reflexivity.
Qed.

Lemma qsum_plus : forall n f g,
  qsum n (fun i => f i + g i) == qsum n f + qsum n g.
Proof.
  induction n as [| m IH]; intros f g; simpl; [ring |].
  rewrite IH; ring.
Qed.

Lemma qsum_scale_l : forall n c f,
  qsum n (fun i => c * f i) == c * qsum n f.
Proof.
  induction n as [| m IH]; intros c f; simpl; [ring |].
  rewrite IH; ring.
Qed.

Lemma qsum_scale_r : forall n c f,
  qsum n (fun i => f i * c) == qsum n f * c.
Proof.
  induction n as [| m IH]; intros c f; simpl; [ring |].
  rewrite IH; ring.
Qed.

Lemma qsum_zero : forall n f,
  (forall i, (i < n)%nat -> f i == 0) -> qsum n f == 0.
Proof.
  induction n as [| m IH]; intros f H; simpl; [reflexivity |].
  rewrite (IH f (fun i Hi => H i (Nat.lt_lt_succ_r _ _ Hi))).
  rewrite (H m (Nat.lt_succ_diag_r m)); ring.
Qed.

Lemma qsum_app : forall a b f,
  qsum (a + b) f == qsum a f + qsum b (fun i => f (a + i)%nat).
Proof.
  intros a b; induction b as [| b IH]; intros f.
  - rewrite Nat.add_0_r; simpl; ring.
  - rewrite Nat.add_succ_r; simpl.
    rewrite IH; ring.
Qed.

Lemma qsum_swap : forall m n f,
  qsum m (fun i => qsum n (fun j => f i j)) ==
  qsum n (fun j => qsum m (fun i => f i j)).
Proof.
  induction m as [| m IH]; intros n f; simpl.
  - rewrite (qsum_zero n (fun _ => 0)); [reflexivity | intros; reflexivity].
  - rewrite (IH n f), <- qsum_plus.
    apply qsum_ext; intros j _; reflexivity.
Qed.

Lemma qsum_mul : forall m n f g,
  qsum m f * qsum n g ==
  qsum m (fun a => qsum n (fun b => f a * g b)).
Proof.
  induction m as [| m IH]; intros n f g; simpl; [ring |].
  rewrite <- IH.
  rewrite (qsum_scale_l n (f m) g); ring.
Qed.

Lemma qsum_delta_l : forall n (a : nat -> Q) j,
  (j < n)%nat ->
  qsum n (fun k => if Nat.eqb k j then a k else 0) == a j.
Proof.
  induction n as [| m IH]; intros a j Hj; [lia | simpl].
  destruct (Nat.eqb m j) eqn:E.
  - apply Nat.eqb_eq in E; subst j.
    rewrite (qsum_zero m).
    + ring.
    + intros i Hi.
      destruct (Nat.eqb i m) eqn:Ei; [apply Nat.eqb_eq in Ei; lia | reflexivity].
  - apply Nat.eqb_neq in E.
    rewrite (IH a j) by lia; ring.
Qed.

Lemma qsum_delta_r : forall n (a : nat -> Q) j,
  (j < n)%nat ->
  qsum n (fun k => if Nat.eqb j k then a k else 0) == a j.
Proof.
  intros n a j Hj.
  rewrite (qsum_ext n _ (fun k => if Nat.eqb k j then a k else 0)).
  - apply qsum_delta_l; exact Hj.
  - intros i _; rewrite Nat.eqb_sym; reflexivity.
Qed.

Lemma qsum_split : forall m n f,
  qsum (m * n) f ==
  qsum m (fun a => qsum n (fun b => f (a * n + b)%nat)).
Proof.
  induction m as [| m IH]; intros n f; simpl; [reflexivity |].
  replace (n + m * n)%nat with (m * n + n)%nat by lia.
  rewrite qsum_app, (IH n f).
  apply Qplus_comp; [apply qsum_ext; intros a _; reflexivity |].
  apply qsum_ext; intros b _.
  replace (m * n + b)%nat with (m * n + b)%nat by lia; reflexivity.
Qed.

(* T16.  The index kit (names verified for 8.20 in the design). *)
Lemma div_add_small : forall a b n,
  (b < n)%nat -> ((a * n + b) / n)%nat = a.
Proof.
  intros a b n Hb.
  assert (Hn : n <> 0%nat) by lia.
  rewrite Nat.div_add_l by exact Hn.
  rewrite Nat.div_small by exact Hb; lia.
Qed.

Lemma mod_add_small : forall a b n,
  (b < n)%nat -> ((a * n + b) mod n)%nat = b.
Proof.
  intros a b n Hb.
  rewrite Nat.add_comm, Nat.Div0.mod_add.
  apply Nat.mod_small; exact Hb.
Qed.

Lemma div_lt : forall i m n,
  (i < m * n)%nat -> (i / n < m)%nat.
Proof.
  intros i m n Hi.
  apply Nat.Div0.div_lt_upper_bound; lia.
Qed.

Lemma mod_lt : forall i m n,
  (i < m * n)%nat -> (i mod n < n)%nat.
Proof.
  intros i m n Hi.
  destruct n as [| n]; [lia |].
  apply Nat.mod_upper_bound; lia.
Qed.

Lemma div_mod_split : forall i n,
  i = ((i / n) * n + i mod n)%nat.
Proof.
  intros i n; pose proof (Nat.div_mod_eq i n); lia.
Qed.

(* ========================================================================== *)
(*  Part 3c — category and strict monoidal laws (T17-T20)                     *)
(* ========================================================================== *)

Lemma mat_eq_refl : forall m n A, mat_eq m n A A.
Proof. intros m n A i j _ _; reflexivity. Qed.

Lemma mat_eq_sym : forall m n A B, mat_eq m n A B -> mat_eq m n B A.
Proof. intros m n A B H i j Hi Hj; symmetry; apply H; assumption. Qed.

Lemma mat_eq_trans : forall m n A B C,
  mat_eq m n A B -> mat_eq m n B C -> mat_eq m n A C.
Proof.
  intros m n A B C H1 H2 i j Hi Hj.
  rewrite (H1 i j Hi Hj); apply H2; assumption.
Qed.

Lemma mat_eq_dims : forall m m' n n' A B,
  m = m' -> n = n' -> mat_eq m n A B -> mat_eq m' n' A B.
Proof. intros; subst; assumption. Qed.

(* T17.  Congruence of the operations w.r.t. mat_eq. *)
Lemma mmul_ext : forall m k n A A' B B',
  mat_eq m k A A' -> mat_eq k n B B' ->
  mat_eq m n (mmul k A B) (mmul k A' B').
Proof.
  intros m k n A A' B B' HA HB i j Hi Hj; unfold mmul.
  apply qsum_ext; intros l Hl.
  rewrite (HA i l Hi Hl), (HB l j Hl Hj); reflexivity.
Qed.

Lemma kron_ext : forall m1 n1 m2 n2 A A' B B',
  mat_eq m1 n1 A A' -> mat_eq m2 n2 B B' ->
  mat_eq (m1 * m2) (n1 * n2) (kron m2 n2 A B) (kron m2 n2 A' B').
Proof.
  intros m1 n1 m2 n2 A A' B B' HA HB i j Hi Hj; unfold kron.
  rewrite (HA _ _ (div_lt _ _ _ Hi) (div_lt _ _ _ Hj)).
  rewrite (HB _ _ (mod_lt _ _ _ Hi) (mod_lt _ _ _ Hj)).
  reflexivity.
Qed.

(* T18.  Category laws (CSC10 §3.1 p. 8). *)
Lemma mmul_idm_l : forall m n A,
  mat_eq m n (mmul m idm A) A.
Proof.
  intros m n A i j Hi Hj; unfold mmul, idm.
  rewrite (qsum_ext m _ (fun l => if Nat.eqb l i then A l j else 0)).
  - exact (qsum_delta_l m (fun l => A l j) i Hi).
  - intros l _.
    rewrite (Nat.eqb_sym i l).
    destruct (Nat.eqb l i); ring.
Qed.

Lemma mmul_idm_r : forall m n A,
  mat_eq m n (mmul n A idm) A.
Proof.
  intros m n A i j Hi Hj; unfold mmul, idm.
  rewrite (qsum_ext n _ (fun l => if Nat.eqb l j then A i l else 0)).
  - exact (qsum_delta_l n (fun l => A i l) j Hj).
  - intros l _.
    destruct (Nat.eqb l j); ring.
Qed.

Lemma mmul_assoc : forall m k l n A B C,
  mat_eq m n (mmul l (mmul k A B) C) (mmul k A (mmul l B C)).
Proof.
  intros m k l n A B C i j Hi Hj; unfold mmul.
  rewrite (qsum_ext l _
    (fun c => qsum k (fun b => A i b * B b c * C c j))).
  2:{ intros c _.
      rewrite <- (qsum_scale_r k (C c j) (fun b => A i b * B b c)).
      apply qsum_ext; intros b _; ring. }
  rewrite qsum_swap.
  apply qsum_ext; intros b _.
  rewrite <- (qsum_scale_l l (A i b) (fun c => B b c * C c j)).
  apply qsum_ext; intros c _; ring.
Qed.

(* T19.  Bifunctoriality / interchange (CSC10 eq. (3) p. 9). *)
Lemma interchange : forall m1 k1 n1 m2 k2 n2 G1 F1 G2 F2,
  mat_eq (m1 * m2) (n1 * n2)
    (mmul (k1 * k2) (kron m2 k2 G1 G2) (kron k2 n2 F1 F2))
    (kron m2 n2 (mmul k1 G1 F1) (mmul k2 G2 F2)).
Proof.
  intros m1 k1 n1 m2 k2 n2 G1 F1 G2 F2 i j Hi Hj.
  unfold mmul, kron.
  rewrite qsum_split.
  rewrite (qsum_ext k1 _
    (fun a => qsum k2 (fun b =>
       (G1 (i / m2)%nat a * F1 a (j / n2)%nat) *
       (G2 (i mod m2)%nat b * F2 b (j mod n2)%nat)))).
  - rewrite <- qsum_mul; reflexivity.
  - intros a Ha; apply qsum_ext; intros b Hb.
    rewrite (div_add_small a b k2 Hb), (mod_add_small a b k2 Hb); ring.
Qed.

Lemma kron_idm : forall m n,
  mat_eq (m * n) (m * n) (kron n n idm idm) idm.
Proof.
  intros m n i j Hi Hj; unfold kron, idm.
  destruct (Nat.eqb i j) eqn:E.
  - apply Nat.eqb_eq in E; subst j.
    rewrite Nat.eqb_refl, Nat.eqb_refl; ring.
  - apply Nat.eqb_neq in E.
    destruct (Nat.eqb (i / n) (j / n)) eqn:E1;
      destruct (Nat.eqb (i mod n) (j mod n)) eqn:E2; try ring.
    apply Nat.eqb_eq in E1; apply Nat.eqb_eq in E2.
    exfalso; apply E.
    rewrite (div_mod_split i n), (div_mod_split j n), E1, E2; reflexivity.
Qed.

(* T20.  STRICT monoidal laws on the nose — the load-bearing lemmas
   that let F and tensor_words bracket tensors differently
   (CSC10 §3.1 eqs (1)-(2)). *)
Lemma kron_assoc : forall m1 n1 m2 n2 m3 n3 A B C,
  mat_eq (m1 * m2 * m3) (n1 * n2 * n3)
    (kron m3 n3 (kron m2 n2 A B) C)
    (kron (m2 * m3) (n2 * n3) A (kron m3 n3 B C)).
Proof.
  intros m1 n1 m2 n2 m3 n3 A B C i j Hi Hj; unfold kron.
  destruct m3 as [| m3']; [lia |].
  destruct n3 as [| n3']; [lia |].
  destruct m2 as [| m2']; [lia |].
  destruct n2 as [| n2']; [lia |].
  set (m3 := S m3') in *; set (n3 := S n3') in *.
  set (m2 := S m2') in *; set (n2 := S n2') in *.
  rewrite (Nat.mul_comm m2 m3), (Nat.mul_comm n2 n3).
  rewrite (Nat.Div0.div_div i m3 m2), (Nat.Div0.div_div j n3 n2).
  rewrite (Nat.Div0.mod_mul_r i m3 m2), (Nat.Div0.mod_mul_r j n3 n2).
  assert (Him : ((i mod m3 + m3 * ((i / m3) mod m2)) / m3)%nat
                = ((i / m3) mod m2)%nat).
  { rewrite Nat.add_comm, <- (Nat.mul_comm ((i / m3) mod m2) m3).
    apply div_add_small.
    apply Nat.mod_upper_bound; unfold m3; lia. }
  assert (Him2 : ((i mod m3 + m3 * ((i / m3) mod m2)) mod m3)%nat
                 = (i mod m3)%nat).
  { rewrite Nat.add_comm, <- (Nat.mul_comm ((i / m3) mod m2) m3).
    apply mod_add_small.
    apply Nat.mod_upper_bound; unfold m3; lia. }
  assert (Hjn : ((j mod n3 + n3 * ((j / n3) mod n2)) / n3)%nat
                = ((j / n3) mod n2)%nat).
  { rewrite Nat.add_comm, <- (Nat.mul_comm ((j / n3) mod n2) n3).
    apply div_add_small.
    apply Nat.mod_upper_bound; unfold n3; lia. }
  assert (Hjn2 : ((j mod n3 + n3 * ((j / n3) mod n2)) mod n3)%nat
                 = (j mod n3)%nat).
  { rewrite Nat.add_comm, <- (Nat.mul_comm ((j / n3) mod n2) n3).
    apply mod_add_small.
    apply Nat.mod_upper_bound; unfold n3; lia. }
  rewrite Him, Him2, Hjn, Hjn2; ring.
Qed.

Lemma kron_unit_l : forall m n A,
  mat_eq m n (kron m n idm A) A.
Proof.
  intros m n A i j Hi Hj; unfold kron, idm.
  rewrite (Nat.div_small i m Hi), (Nat.div_small j n Hj); simpl.
  rewrite (Nat.mod_small i m Hi), (Nat.mod_small j n Hj); ring.
Qed.

Lemma kron_unit_r : forall m n A,
  mat_eq m n (kron 1 1 A idm) A.
Proof.
  intros m n A i j Hi Hj; unfold kron, idm.
  rewrite Nat.div_1_r, Nat.div_1_r, Nat.mod_1_r, Nat.mod_1_r; simpl; ring.
Qed.

(* ========================================================================== *)
(*  Part 3d — the snake equations, inner product, trace (T21-T23)             *)
(* ========================================================================== *)

(* Digit decomposition of an index below d*(d*d). *)
Lemma three_digits : forall d l,
  (0 < d)%nat -> (l < d * (d * d))%nat ->
  ((l / (d * d)) < d)%nat /\
  (((l mod (d * d)) / d) < d)%nat /\
  (((l mod (d * d)) mod d) < d)%nat /\
  l = ((l / (d * d)) * (d * d) +
       (((l mod (d * d)) / d) * d + (l mod (d * d)) mod d))%nat /\
  (l / d)%nat = ((l / (d * d)) * d + (l mod (d * d)) / d)%nat /\
  (l mod d)%nat = ((l mod (d * d)) mod d)%nat.
Proof.
  intros d l Hd Hl.
  set (a := (l / (d * d))%nat).
  set (r := (l mod (d * d))%nat).
  set (b := (r / d)%nat).
  set (c := (r mod d)%nat).
  assert (Ha : (a < d)%nat) by (apply div_lt; exact Hl).
  assert (Hr : (r < d * d)%nat) by (apply mod_lt with (m := d); exact Hl).
  assert (Hb : (b < d)%nat) by (apply div_lt; exact Hr).
  assert (Hc : (c < d)%nat) by (apply mod_lt with (m := d); exact Hr).
  assert (Hlr : l = (a * (d * d) + r)%nat) by (apply div_mod_split).
  assert (Hrbc : r = (b * d + c)%nat) by (apply div_mod_split).
  assert (Hflat : l = ((a * d + b) * d + c)%nat).
  { rewrite Hlr, Hrbc; ring. }
  repeat split; try assumption.
  - lia.
  - rewrite Hflat; apply div_add_small; exact Hc.
  - rewrite Hflat; apply mod_add_small; exact Hc.
Qed.

(* T21.  The snake (yanking) equations, at every dimension (CSC10 §3.3
   p. 11).  With V^l = V^r = V there are two computational shapes; the
   four named equations of the calculus map onto them (see F_deq). *)
Lemma snake_A : forall d,
  mat_eq d d
    (mmul (d * (d * d))
       (kron 1 (d * d) idm (eps d))
       (kron d d (eta d) idm))
    idm.
Proof.
  intros d i j Hi Hj.
  assert (Hd : (0 < d)%nat) by lia.
  unfold mmul.
  rewrite (qsum_ext (d * (d * d)) _
    (fun l => if Nat.eqb l (i * (d * d) + (i * d + i)) then
                (if Nat.eqb i j then 1 else 0) else 0)).
  { apply (qsum_delta_l (d * (d * d))
            (fun _ => if Nat.eqb i j then 1 else 0)
            (i * (d * d) + (i * d + i))%nat); nia. }
  intros l Hl.
  destruct (three_digits d l Hd Hl) as
    [Ha [Hb [Hc [Hdec [Hld Hlm]]]]].
  set (a := (l / (d * d))%nat) in *.
  set (b := ((l mod (d * d)) / d)%nat) in *.
  set (c := ((l mod (d * d)) mod d)%nat) in *.
  unfold kron, idm, eps, eta.
  rewrite Nat.div_1_r.
  rewrite Hld, (div_add_small a b d Hb), (mod_add_small a b d Hb).
  rewrite Hlm.
  rewrite (Nat.mod_small j d Hj).
  fold a b c.
  destruct (Nat.eqb l (i * (d * d) + (i * d + i))) eqn:El.
  - apply Nat.eqb_eq in El.
    assert (Hai : a = i).
    { unfold a; rewrite El; apply div_add_small; nia. }
    assert (Hri : (l mod (d * d))%nat = (i * d + i)%nat).
    { rewrite El; apply mod_add_small; nia. }
    assert (Hbi : b = i).
    { unfold b; rewrite Hri; apply div_add_small; lia. }
    assert (Hci : c = i).
    { unfold c; rewrite Hri; apply mod_add_small; lia. }
    rewrite Hai, Hbi, Hci, !Nat.eqb_refl.
    destruct (Nat.eqb i j); ring.
  - apply Nat.eqb_neq in El.
    destruct (Nat.eqb i a) eqn:E1;
    destruct (Nat.eqb b c) eqn:E2;
    destruct (Nat.eqb a b) eqn:E3;
    destruct (Nat.eqb c j) eqn:E4; try ring.
    apply Nat.eqb_eq in E1; apply Nat.eqb_eq in E2;
    apply Nat.eqb_eq in E3; apply Nat.eqb_eq in E4.
    exfalso; apply El.
    assert (Hai : a = i) by lia.
    assert (Hbi : b = i) by lia.
    assert (Hci : c = i) by lia.
    rewrite Hdec, Hai, Hbi, Hci; reflexivity.
Qed.

Lemma snake_B : forall d,
  mat_eq d d
    (mmul (d * (d * d))
       (kron d d (eps d) idm)
       (kron (d * d) 1 idm (eta d)))
    idm.
Proof.
  intros d i j Hi Hj.
  assert (Hd : (0 < d)%nat) by lia.
  unfold mmul.
  rewrite (qsum_ext (d * (d * d)) _
    (fun l => if Nat.eqb l (j * (d * d) + (j * d + j)) then
                (if Nat.eqb i j then 1 else 0) else 0)).
  { apply (qsum_delta_l (d * (d * d))
            (fun _ => if Nat.eqb i j then 1 else 0)
            (j * (d * d) + (j * d + j))%nat); nia. }
  intros l Hl.
  destruct (three_digits d l Hd Hl) as
    [Ha [Hb [Hc [Hdec [Hld Hlm]]]]].
  set (a := (l / (d * d))%nat) in *.
  set (b := ((l mod (d * d)) / d)%nat) in *.
  set (c := ((l mod (d * d)) mod d)%nat) in *.
  unfold kron, idm, eps, eta.
  rewrite Nat.div_1_r.
  rewrite Hld, (div_add_small a b d Hb), (mod_add_small a b d Hb).
  rewrite Hlm.
  rewrite (Nat.mod_small i d Hi).
  fold a b c.
  destruct (Nat.eqb l (j * (d * d) + (j * d + j))) eqn:El.
  - apply Nat.eqb_eq in El.
    assert (Haj : a = j).
    { unfold a; rewrite El; apply div_add_small; nia. }
    assert (Hrj : (l mod (d * d))%nat = (j * d + j)%nat).
    { rewrite El; apply mod_add_small; nia. }
    assert (Hbj : b = j).
    { unfold b; rewrite Hrj; apply div_add_small; lia. }
    assert (Hcj : c = j).
    { unfold c; rewrite Hrj; apply mod_add_small; lia. }
    rewrite Haj, Hbj, Hcj, !Nat.eqb_refl.
    destruct (Nat.eqb i j); ring.
  - apply Nat.eqb_neq in El.
    destruct (Nat.eqb a b) eqn:E1;
    destruct (Nat.eqb i c) eqn:E2;
    destruct (Nat.eqb a j) eqn:E3;
    destruct (Nat.eqb b c) eqn:E4; try ring.
    apply Nat.eqb_eq in E1; apply Nat.eqb_eq in E2;
    apply Nat.eqb_eq in E3; apply Nat.eqb_eq in E4.
    exfalso; apply El.
    assert (Haj : a = j) by lia.
    assert (Hbj : b = j) by lia.
    assert (Hcj : c = j) by lia.
    rewrite Hdec, Haj, Hbj, Hcj; reflexivity.
Qed.

(* T22.  eps is the inner product (CSC10 eq. (5) p. 13). *)
Lemma eps_general : forall d (c : nat -> nat -> Q),
  mmul (d * d) (eps d) c 0%nat 0%nat ==
  qsum d (fun i => c (i * d + i)%nat 0%nat).
Proof.
  intros d c; unfold mmul.
  rewrite qsum_split.
  rewrite (qsum_ext d _
    (fun a => qsum d (fun b =>
       if Nat.eqb a b then c (a * d + b)%nat 0%nat else 0))).
  - apply qsum_ext; intros a Ha.
    rewrite (qsum_delta_r d (fun b => c (a * d + b)%nat 0%nat) a Ha).
    reflexivity.
  - intros a Ha; apply qsum_ext; intros b Hb.
    unfold eps.
    rewrite (div_add_small a b d Hb), (mod_add_small a b d Hb).
    destruct (Nat.eqb a b); ring.
Qed.

Lemma eps_inner : forall d v w,
  mmul (d * d) (eps d) (kron d 1 v w) 0%nat 0%nat == inner d v w.
Proof.
  intros d v w; rewrite eps_general; unfold inner.
  apply qsum_ext; intros i Hi.
  unfold kron.
  rewrite (div_add_small i i d Hi), (mod_add_small i i d Hi).
  reflexivity.
Qed.

(* T23.  The trace: eps . eta = the dimension, as a scalar
   (CSC10 p. 12). *)
Lemma qsum_const1 : forall n,
  qsum n (fun _ => 1) == inject_Z (Z.of_nat n).
Proof.
  induction n as [| m IH]; [reflexivity |].
  change (qsum (S m) (fun _ => 1)) with (qsum m (fun _ => 1) + 1).
  rewrite IH, Nat2Z.inj_succ, <- Z.add_1_l, inject_Z_plus; ring.
Qed.

Lemma trace_eps_eta : forall d,
  mmul (d * d) (eps d) (eta d) 0%nat 0%nat == inject_Z (Z.of_nat d).
Proof.
  intros d; rewrite eps_general.
  rewrite (qsum_ext d _ (fun _ => 1)).
  - apply qsum_const1.
  - intros i Hi; unfold eta.
    rewrite (div_add_small i i d Hi), (mod_add_small i i d Hi).
    rewrite Nat.eqb_refl; reflexivity.
Qed.

(* ========================================================================== *)
(*  Part 4b — Soundness: F respects the equational theory (T28-T30)           *)
(* ========================================================================== *)

Section Soundness.

Variable B : Type.
Variable dim : B -> nat.

(* T28.  The substantive theorem: derivations equal in the free strict
   compact closed category have equal matrices — well-definedness of the
   meaning map relative to the calculus, for ALL reductions (CSC10 §3.1
   p. 9, sound direction of coherence; PL07 Prop. 1). *)
Theorem F_deq : forall (p q p' q' : Ty B) (d : Red p q) (d' : Red p' q'),
  deq d d' ->
  p = p' /\ q = q' /\
  mat_eq (dimT dim q) (dimT dim p) (F dim d) (F dim d').
Proof.
  intros p q p' q' d d' H; induction H.
  - (* refl *)
    split; [reflexivity | split; [reflexivity | apply mat_eq_refl]].
  - (* sym *)
    repeat match goal with IH : _ /\ _ |- _ => destruct IH end; subst.
    split; [reflexivity | split; [reflexivity |]].
    apply mat_eq_sym; assumption.
  - (* trans *)
    repeat match goal with IH : _ /\ _ |- _ => destruct IH end; subst.
    split; [reflexivity | split; [reflexivity |]].
    eapply mat_eq_trans; eassumption.
  - (* cong_trans *)
    repeat match goal with IH : _ /\ _ |- _ => destruct IH end; subst.
    split; [reflexivity | split; [reflexivity |]].
    simpl; apply mmul_ext; assumption.
  - (* cong_tensor *)
    repeat match goal with IH : _ /\ _ |- _ => destruct IH end; subst.
    split; [reflexivity | split; [reflexivity |]].
    rewrite !(dimT_app B dim); simpl; apply kron_ext; assumption.
  - (* assoc *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; apply mat_eq_sym, mmul_assoc.
  - (* unit_l *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; apply mmul_idm_r.
  - (* unit_r *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; apply mmul_idm_l.
  - (* tensor_assoc *)
    split; [symmetry; apply app_assoc |
            split; [symmetry; apply app_assoc |]].
    rewrite !(dimT_app B dim); simpl.
    rewrite !(dimT_app B dim).
    apply kron_assoc.
  - (* tensor_unit_l *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; apply kron_unit_l.
  - (* tensor_unit_r *)
    split; [apply app_nil_r | split; [apply app_nil_r |]].
    apply (mat_eq_dims (dimT dim q) _ (dimT dim p) _);
      [rewrite app_nil_r; reflexivity |
       rewrite app_nil_r; reflexivity |].
    simpl; apply kron_unit_r.
  - (* tensor_refl *)
    split; [reflexivity | split; [reflexivity |]].
    rewrite !(dimT_app B dim); simpl; apply kron_idm.
  - (* interchange *)
    split; [reflexivity | split; [reflexivity |]].
    rewrite !(dimT_app B dim); simpl.
    rewrite !(dimT_app B dim).
    apply interchange.
  - (* cast *)
    match goal with
    | E1 : _ = _, E2 : _ = _ |- _ => destruct E1, E2
    end.
    split; [reflexivity | split; [reflexivity | apply mat_eq_refl]].
  - (* snake_1 *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; rewrite !Nat.mul_1_r; apply snake_A.
  - (* snake_2 *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; rewrite !Nat.mul_1_r; apply snake_B.
  - (* snake_3 *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; rewrite !Nat.mul_1_r; apply snake_B.
  - (* snake_4 *)
    split; [reflexivity | split; [reflexivity |]].
    simpl; rewrite !Nat.mul_1_r; apply snake_A.
Qed.

(* T30.  Meanings are invariant under deq — the brief's
   well-definedness statement at sentence level (CSC10 Def 3.2;
   CGS13 Def 4.2). *)
Theorem meaning_deq : forall (p q p' q' : Ty B)
  (d : Red p q) (d' : Red p' q') ws,
  deq d d' ->
  mat_eq (dimT dim q) 1 (meaning dim d ws) (meaning dim d' ws).
Proof.
  intros p q p' q' d d' ws H.
  destruct (F_deq p q p' q' d d' H) as [E1 [E2 M]]; subst.
  unfold meaning; apply mmul_ext; [exact M | apply mat_eq_refl].
Qed.

End Soundness.

(* T29.  Corollary at the example grammar: all readings of "John likes
   Mary" have the same matrix, for EVERY dimension assignment
   (T12 + T28); the fixed-dim reflection is
   ExModel.readings_agree_computationally. *)
Theorem F_tv_orders : forall (dim : Examples.basic -> nat),
  mat_eq (dimT dim [Examples.s])
         (dimT dim [Examples.n; radj Examples.n; Examples.s;
                    ladj Examples.n; Examples.n])
         (F dim Examples.tv_red_subj) (F dim Examples.tv_red) /\
  mat_eq (dimT dim [Examples.s])
         (dimT dim [Examples.n; radj Examples.n; Examples.s;
                    ladj Examples.n; Examples.n])
         (F dim Examples.tv_red_obj) (F dim Examples.tv_red) /\
  mat_eq (dimT dim [Examples.s])
         (dimT dim [Examples.n; radj Examples.n; Examples.s;
                    ladj Examples.n; Examples.n])
         (F dim Examples.tv_red_alt) (F dim Examples.tv_red).
Proof.
  intros dim.
  refine (conj _ (conj _ _)).
  - exact (proj2 (proj2 (F_deq _ dim _ _ _ _ _ _ Examples.deq_tv_subj))).
  - exact (proj2 (proj2 (F_deq _ dim _ _ _ _ _ _ Examples.deq_tv_obj))).
  - exact (proj2 (proj2 (F_deq _ dim _ _ _ _ _ _ Examples.deq_tv_alt))).
Qed.

(* ========================================================================== *)
(*  Part 1c — compound adjoint laws (T4, T7, T8): last of MUST, nothing       *)
(*  downstream depends on them (build-order note in the design)               *)
(* ========================================================================== *)

Section CompoundAdjoints.

Variable B : Type.

(* D8, generalized cast-light forms (Lambek ch. 4 p. 9: the telescoping
   (xy)^l (xy) -> y^l (x^l x) y -> y^l y -> 1; PL07 (3.3)). *)
Lemma cup_l_gen : forall (p u : Ty B), Red (ladj_ty p ++ p ++ u) u.
Proof.
  induction p as [| a p' IH]; intros u.
  - exact (red_refl u).
  - refine (red_cast _ eq_refl
      (red_trans (red_subst (ladj_ty p') (p' ++ u) (red_cup_l a))
                 (IH u))).
    unfold ladj_ty; simpl map; simpl rev.
    rewrite <- app_assoc; reflexivity.
Qed.

Lemma cup_r_gen : forall (p u : Ty B), Red (p ++ radj_ty p ++ u) u.
Proof.
  induction p as [| a p' IH]; intros u.
  - exact (red_refl u).
  - refine (red_cast _ eq_refl
      (red_trans
         (red_tensor (red_refl [a]) (IH ([radj a] ++ u)))
         (red_tensor (red_cup_r a) (red_refl u)))).
    unfold radj_ty; simpl map; simpl rev.
    simpl app.
    rewrite <- app_assoc; reflexivity.
Qed.

Lemma cap_l_gen : forall p : Ty B, Red [] (p ++ ladj_ty p).
Proof.
  induction p as [| a p' IH].
  - exact (red_refl []).
  - refine (red_cast eq_refl _
      (red_trans (red_cap_l a)
         (red_subst [a] [ladj a] IH))).
    unfold ladj_ty; simpl map; simpl rev.
    simpl app.
    rewrite app_assoc; reflexivity.
Qed.

Lemma cap_r_gen : forall p : Ty B, Red [] (radj_ty p ++ p).
Proof.
  induction p as [| a p' IH].
  - exact (red_refl []).
  - refine (red_cast eq_refl _
      (red_trans IH
         (red_subst (radj_ty p') p' (red_cap_r a)))).
    unfold radj_ty; simpl map; simpl rev.
    rewrite <- app_assoc; reflexivity.
Qed.

(* T4.  The compound adjoint laws at the order level. *)
Theorem Le_cup_l_ty : forall p : Ty B, Le (ladj_ty p ++ p) [].
Proof.
  intros p; constructor.
  refine (red_cast _ eq_refl (cup_l_gen p [])).
  rewrite app_nil_r; reflexivity.
Qed.

Theorem Le_cup_r_ty : forall p : Ty B, Le (p ++ radj_ty p) [].
Proof.
  intros p; constructor.
  refine (red_cast _ eq_refl (cup_r_gen p [])).
  rewrite app_nil_r; reflexivity.
Qed.

Theorem Le_cap_l_ty : forall p : Ty B, Le [] (p ++ ladj_ty p).
Proof. intros p; exact (inhabits (cap_l_gen p)). Qed.

Theorem Le_cap_r_ty : forall p : Ty B, Le [] (radj_ty p ++ p).
Proof. intros p; exact (inhabits (cap_r_gen p)). Qed.

(* T7.  Contravariance of the adjoints (L08 ch. 27 (3) p. 75:
   y^l = y^l 1 -> y^l x x^l -> y^l y x^l -> 1 x^l). *)
Theorem Le_contra_l : forall p q : Ty B,
  Le p q -> Le (ladj_ty q) (ladj_ty p).
Proof.
  intros p q [d]; constructor.
  refine (red_trans
    (red_cast (app_nil_r (ladj_ty q)) eq_refl
       (red_tensor (red_refl (ladj_ty q)) (cap_l_gen p)))
    (red_trans
       (red_subst (ladj_ty q) (ladj_ty p) d)
       (cup_l_gen q (ladj_ty p)))).
Qed.

Theorem Le_contra_r : forall p q : Ty B,
  Le p q -> Le (radj_ty q) (radj_ty p).
Proof.
  intros p q [d]; constructor.
  refine (red_trans
    (red_tensor (cap_r_gen p) (red_refl (radj_ty q)))
    (red_trans
       (red_cast _ eq_refl (red_subst (radj_ty p) (radj_ty q) d))
       (red_cast eq_refl (app_nil_r (radj_ty p))
          (red_tensor (red_refl (radj_ty p))
             (red_cast _ eq_refl (cup_r_gen q [])))))).
  - rewrite app_assoc; reflexivity.
  - rewrite app_nil_r; reflexivity.
Qed.

(* T8.  Adjoints are unique up to mutual reduction (L08 (14), ch. 27
   (1); CSC10 p. 5). *)
Theorem adjoint_unique_l : forall (y p : Ty B),
  Le (y ++ p) [] -> Le [] (p ++ y) ->
  Le y (ladj_ty p) /\ Le (ladj_ty p) y.
Proof.
  intros y p [d1] [d2]; split; constructor.
  - refine (red_trans
      (red_cast (app_nil_r y) eq_refl
         (red_tensor (red_refl y) (cap_l_gen p)))
      (red_cast _ eq_refl
         (red_tensor d1 (red_refl (ladj_ty p))))).
    rewrite app_assoc; reflexivity.
  - refine (red_trans
      (red_cast (app_nil_r (ladj_ty p)) eq_refl
         (red_tensor (red_refl (ladj_ty p)) d2))
      (red_cast _ eq_refl
         (red_tensor
            (red_cast (f_equal (app (ladj_ty p)) (app_nil_r p)) eq_refl
               (cup_l_gen p []))
            (red_refl y)))).
    symmetry; apply app_assoc.
Qed.

End CompoundAdjoints.

(* ========================================================================== *)
(*  Part 6 — Assumption audit                                                 *)
(* ========================================================================== *)
(* Output under Coq 8.20.1 (2026-09-05): every theorem below prints
   "Closed under the global context" — zero axioms, no classical
   principles, no extensionality (ARTIFACT note: constructive and
   axiom-free by design; setoid equalities everywhere). *)
Print Assumptions le_not_antisymmetric.
Print Assumptions deq_endpoints.
Print Assumptions Examples.deq_tv_subj.
Print Assumptions Examples.deq_tv_obj.
Print Assumptions Examples.deq_tv_alt.
Print Assumptions Examples.Le_neg.
Print Assumptions mmul_assoc.
Print Assumptions interchange.
Print Assumptions kron_assoc.
Print Assumptions kron_idm.
Print Assumptions snake_A.
Print Assumptions snake_B.
Print Assumptions eps_inner.
Print Assumptions trace_eps_eta.
Print Assumptions F_deq.
Print Assumptions meaning_deq.
Print Assumptions F_tv_orders.
Print Assumptions Le_cup_l_ty.
Print Assumptions Le_contra_l.
Print Assumptions adjoint_unique_l.
Print Assumptions ExModel.ex1_true.
Print Assumptions ExModel.ex1b_true.
Print Assumptions ExModel.ex3_graded.
Print Assumptions ExModel.ex5_loves_likesg.
Print Assumptions ExModel.readings_agree_computationally.
